'''
Make sure you pass all of these tests before creating the 
DeckReader class

'''

'''

DO NOT EDIT THIS FILE UNLESS TOLD TO DO SO


'''


import random

from flash_cards import *


def test_deck_init_name():
    alpha = random.choice("abcdefghijklmnop")
    test_deck = Deck("python_vocab.csv", alpha)
    assert test_deck.name == alpha

def test_deck_load_deck():
    test_deck = Deck("python_vocab.csv", "a name")
    ## Check other cards too, make sure they are correct
    assert len(test_deck.cards) <= 5
    assert test_deck.cards[0].front == "integer"
    assert test_deck.cards[0].back == "Name the data type: -3 -2 -1 0 1 2 3 ..."
    assert test_deck.cards[1].front == "float"
    assert test_deck.cards[1].back == "Name the data type: 1.1 1.0 -2.3 100.0..."
    assert test_deck.cards[2].front == "string"
    assert test_deck.cards[2].back == 'Name the data type: "Hello world" "C" "c"...'

def test_deck_rename():
    test_deck = Deck("python_vocab.csv", "a name")
    assert test_deck.name == "a name"
    alpha = random.choice("abcdefghijklmnopqrstuvwxyz")
    test_deck.rename(alpha)
    assert test_deck.name == alpha

def test_deck_file_name():
    test_deck = Deck("python_vocab.csv", "python")
    assert test_deck.file_name == "python_vocab.csv"
